// <auto-generated />
using MasterAnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasterAnimalShelter.Migrations
{
    [DbContext(typeof(MasterAnimalShelterContext))]
    [Migration("20200403183143_AnimalPhotos")]
    partial class AnimalPhotos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MasterAnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<bool>("LookingForSlave");

                    b.Property<string>("Name");

                    b.Property<string>("Personality");

                    b.Property<string>("Photo");

                    b.Property<int>("PowerStatus");

                    b.Property<string>("Type");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 123,
                            Gender = "male",
                            LookingForSlave = true,
                            Name = "Cornelious",
                            Personality = "stoic",
                            Photo = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Florida_Box_Turtle_Digon3_re-edited.jpg/440px-Florida_Box_Turtle_Digon3_re-edited.jpg",
                            PowerStatus = 75,
                            Type = "turtle"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 8,
                            Gender = "male",
                            LookingForSlave = true,
                            Name = "Jasper",
                            Personality = "mischevious",
                            Photo = "https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/other/cat_weight_other/1800x1200_cat_weight_other.jpg?resize=600px:*",
                            PowerStatus = 38,
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Gender = "female",
                            LookingForSlave = false,
                            Name = "Shiba",
                            Personality = "insightful",
                            Photo = "https://cdn.wallpapersafari.com/37/15/YsU5Ce.jpg",
                            PowerStatus = 40,
                            Type = "hamster"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
